### PR TITLE
Minimum pyasn1 dependency

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
This sort of fixes #5

**Comment by philipkershaw** [comment]
Sorry missed this one for current release but will get it integrated soon.

**Comment by jayvdb** [comment]
Ok. Ill rebase it tomorrow.

**Comment by jayvdb** [comment]
Not wanted.

**Comment by jayvdb** [comment]
Travis CI commit sent as separate PR #12

**Pull request closed without merging**
